disabled_rules: # rule identifiers to exclude from running
  # - type_name
  # - line_length
  # variable_name
  - trailing_whitespace
  - closure_parameter_position
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - affective-chat/Extensions & Helpers/ActivityIndicator.swift
  - affective-chat/Extensions & Helpers/CLLocationManager+Rx.swift
  - affective-chat/Extensions & Helpers/RxCLLocationManagerDelegateProxy.swift
# force_cast: warning
# force_try: warning
# line_length: 
#   warning: 100
#   error: 150
# type_body_length:
#   warning: 250
#   error: 400
# file_length:
#   warning: 500
#   error: 1000
# variable_name:
#   excluded:
#     - i