# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'affective-chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for affective-chat
  pod 'RxSwift',                  '~> 4.0'
  pod 'RxCocoa',                  '~> 4.0'
  pod 'RxSwiftExt'
  pod 'RxOptional'
  pod 'RxGesture'
  pod 'RxDataSources'
  pod 'RxKeyboard'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'
  pod 'PureLayout'
  pod 'Zip', '~> 1.0'
  pod 'SwiftyBeaver'
  pod 'SwiftLint'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Socket.IO-Client-Swift'

end
