# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'affective-chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for affective-chat
  pod 'RxSwift',                  '~> 4.0'
  pod 'RxCocoa',                  '~> 4.0'
  pod 'Moya/RxSwift'
  pod 'Moya-ObjectMapper/RxSwift'

end
